mingle-rails5/config/routes.rb
#  Copyright 2020 ThoughtWorks, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/hello', to: 'welcome#hello'
  root 'projects#index', :conditions => {:method => :get}

  scope :user_display_preference, controller: :user_display_preference do
    post 'update_user_display_preference'
    post 'update_show_deactived_users', action: :update_show_deactivated_users
    post 'update_holiday_effects_preference'
    post 'update_user_project_preference'
  end

  get '/saas_tos/show', to: 'saas_tos#show'
  get '/license/warn', to: 'license#warn'
  get '/license/show', to: 'license#show'


  get '/account/edit', to: 'account#edit'
  get '/account/downgrade', to: 'account#downgrade'

  post '/saas_tos/accept', to: 'saas_tos#accept'

  namespace :api, path: 'api/internal' do
    resources :programs, only: [:index] do
      resources :backlog_objectives, except: [:edit, :new, :create], param: :number do
        post :plan, :change_plan, on: :member
        collection do
          post :reorder, :create
        end
      end

      resources :objective_property_definitions, only: [:create]
      resources :objective_types, only: [:update]

      resources :program_memberships, except: [:edit, :new] do
        post :create
        collection do
          post :bulk_remove, :bulk_update
        end
      end
    end
    resources :users, except: [:new, :create, :edit]

    get '/users/:user_login/projects', to: 'users#projects', as: :user_projects
  end

  resources :projects

  get '/programs/:program_id/backlog_objectives', to: 'backlog_objectives#index', as: :program_backlog_objectives

  resources :install, only: [:index]
  get '/projects/:project_id/team/show_user_selector', to: 'team#show_user_selector'

  resources :programs, only: [:index] do
    resources :plan, only: [:index]
    get :team, to: 'program_memberships#index', as: :memberships, get_with_projects: true
    get :projects, to: 'program_projects#index', as: :projects
    get :dependencies, to: 'program_dependencies#index', as: :dependencies
    get :settings, to: 'program_settings#index', as: :settings
  end

  resource :profile, controller: :profile do
    get 'login', action: :login, as: 'login'
    post 'login', action: :login
    get 'logout', action: :login, as: 'logout'
    get 'show/:user_id', action: :show, as: :user
    get 'forgot_password', action: :forgot_password
  end

  resource :feedback, only: [:new, :create]
  get 'about/contact_us', to: 'about#contact_us', as: :contact_us


  if Rails.env.test?
    get '/call_me_in_test', to: 'dummy#call_me_in_test'
    post '/call_me_in_test', to: 'dummy#call_me_in_test'
    get '/api/:api_version/call_me_in_test', to: 'dummy#call_me_in_test', format: 'xml'
    post '/api/:api_version/call_me_in_test', to: 'dummy#call_me_in_test', format: 'xml'
    get '/raise_exception_for_test', to: 'dummy#raise_exception_for_test'
    get '/call_me_in_test', to: 'dummy#call_me_in_test'
    get '/check_in_test', to: 'dummy_planner_application#check_in_test'
  end
end

mingle-rails5/app/views/layouts/planner/_program_nav.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<div id="header-pills">
  <ul class="clear_float">
    <li class="<%= header_pill_class('program_wall', selected_tab) %>"><%= link_to 'Program Wall', program_backlog_objectives_path(@program.identifier) %></li>
    <li class="<%= header_pill_class('timeline', selected_tab) %>"><%= link_to 'Plan', program_plan_index_path(@program.identifier) %></li>
    <li class="<%= header_pill_class('program_project', selected_tab) %>"><%= link_to 'Projects', program_projects_path(@program.identifier) %></li>
    <li class="<%= header_pill_class('team', selected_tab) %>"><%= link_to 'Team', program_memberships_path(@program.identifier) %></li>
    <li class="<%= header_pill_class('dependencies', selected_tab) %>"><%= link_to 'Dependencies', program_dependencies_path(@program.identifier), :class => 'multiple-dependencies-icon'%></li>
    <%- if MingleConfiguration.program_settings_enabled? && is_admin?(@program, User.current) -%>
      <li class="<%= header_pill_class('program_settings', selected_tab) %>"><%= link_to 'Program Settings', program_settings_path(@program.identifier) %></li>
    <% end %>
  </ul>
</div>

mingle-rails5/app/views/layouts/planner/application.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<!DOCTYPE html>
<html data-rev="<%= MINGLE_REVISION -%>">
  <head>
    <meta http-equiv="Content-Style-Type" content="text/css" />
    <meta charset="utf-8">
    <script src="/javascripts/ckeditor_4_8/ckeditor.js"></script>
	  <%= csrf_meta_tag %>
    <title>
      <%= page_title %>
    </title>
    <%= rails2_compatible_stylesheet_link_tag(:sprockets_planner_css) %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= render :partial => 'layouts/metrics' %>

    <% if Rails.env.test? || Rails.env.development? -%>
      <style type="text/css">
        #javascript-errors {
          margin: 0;
          padding: 0;
          border: none;
          position: fixed;
          top: 0;
          left: 0;
          background: black;
          color: red;
          font-weight: bold;
          text-align: left;
          display: none;
        }

        #javascript-errors a {
          color: yellow;
        }
      </style>
      <%= raw javascript_include_tag("/javascripts/debug/errors.js") %>
    <% end -%>
    <%= rails2_compatible_javascript_include_tag(:sprockets_app_rails_5_js) %>
    <%= javascript_with_rescue %Q{
      MingleJavascript.env = #{Rails.env.to_s.to_json};
      window.docLinkHandler = new LinkHandler(['content']);
      window.MingleColorPalette = #{Color.defaults.to_json};
    } %>
    <link rel="shortcut icon" href="<%= image_path('/favicon.ico') %>" />
    <link rel="apple-touch-icon" href="<%= image_path('/apple-touch-icon.png') %>" />
    <% if Rails.env.test? %>
      <%= javascript_with_rescue "Date.clockNow = #{Clock.now.milliseconds};" %>
      <%= javascript_with_rescue "LocaleDate.timezoneOffset = #{Clock.client_timezone_offset};" if Clock.client_timezone_offset %>
      <%= javascript_include_tag("/javascripts/test-only/thirdparty/jquery.simulate.js") %>
      <%= javascript_include_tag("/javascripts/test-only/thirdparty/jquery.simulate.ext.js") %>
      <%= javascript_include_tag("/javascripts/test-only/thirdparty/jquery.simulate.drag-n-drop.js") %>
    <% end -%>
  </head>
  <body id="<%= controller.controller_name.dup << '_' << controller.action_name %>" class="<%= params[:controller] %>" data-show-holiday-fun="<%=MingleConfiguration.show_holiday_fun?(user_preference(:i_hate_holidays)) -%>"
  data-holiday-name="<%= MingleConfiguration.show_holiday_fun?(user_preference(:i_hate_holidays)) ? MingleConfiguration.latest_holiday : '' -%>"
  data-hover-logo-link="<%= MingleConfiguration.holiday_logo_link.nil? ? '' : MingleConfiguration.holiday_logo_link -%>"
  data-metrics="<%= metrics_data -%>"
  >
    <%= render :partial => 'layouts/application_hd' %>
    <div id="content">

      <%= yield :page_header %>
      <div class="content">
        <%= yield :content_header %>
        <%= render :partial => 'layouts/flash' %>
        <%= render :partial => 'layouts/readonly_warning' %>
        <%= yield %>
      </div>
    </div>
    <%= render :partial => 'layouts/foot_bar' %>

    <div id="content_overlay" style='background-color: white; opacity: 0.7; display:none; position:absolute'></div>
    <div style="display:none"><%= render :partial => 'shared/lightbox_loading_message' %></div>
    <%= render :partial => 'shared/user_notification' %>

    <%= render_buffered_javascript %>
  </body>
</html>

mingle-rails5/app/views/layouts/planner/in_program.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<% content_for :program_name do  %>
  <%= link_to @program.name, programs_path_with_program(@program), id: 'header_plan_name', class: 'header-name' %>
<% end %>

<% content_for :header_pills do  %>
  <%= render partial: 'layouts/planner/program_nav', locals: { selected_tab: ActiveSupport::StringInquirer.new(yield(:selected_tab)) } %>
<% end %>

<%= render file: 'layouts/planner/application' %>