mingle-rails5/config/routes.rb
#  Copyright 2020 ThoughtWorks, Inc.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/hello', to: 'welcome#hello'
  root 'projects#index', :conditions => {:method => :get}

  scope :user_display_preference, controller: :user_display_preference do
    post 'update_user_display_preference'
    post 'update_show_deactived_users', action: :update_show_deactivated_users
    post 'update_holiday_effects_preference'
    post 'update_user_project_preference'
  end

  get '/saas_tos/show', to: 'saas_tos#show'
  get '/license/warn', to: 'license#warn'
  get '/license/show', to: 'license#show'


  get '/account/edit', to: 'account#edit'
  get '/account/downgrade', to: 'account#downgrade'

  post '/saas_tos/accept', to: 'saas_tos#accept'

  namespace :api, path: 'api/internal' do
    resources :programs, only: [:index] do
      resources :backlog_objectives, except: [:edit, :new, :create], param: :number do
        post :plan, :change_plan, on: :member
        collection do
          post :reorder, :create
        end
      end

      resources :objective_property_definitions, only: [:create]
      resources :objective_types, only: [:update]

      resources :program_memberships, except: [:edit, :new] do
        post :create
        collection do
          post :bulk_remove, :bulk_update
        end
      end
    end
    resources :users, except: [:new, :create, :edit]

    get '/users/:user_login/projects', to: 'users#projects', as: :user_projects
  end

  resources :projects

  get '/programs/:program_id/backlog_objectives', to: 'backlog_objectives#index', as: :program_backlog_objectives

  resources :install, only: [:index]
  get '/projects/:project_id/team/show_user_selector', to: 'team#show_user_selector'

  resources :programs, only: [:index] do
    resources :plan, only: [:index]
    get :team, to: 'program_memberships#index', as: :memberships, get_with_projects: true
    get :projects, to: 'program_projects#index', as: :projects
    get :dependencies, to: 'program_dependencies#index', as: :dependencies
    get :settings, to: 'program_settings#index', as: :settings
  end

  resource :profile, controller: :profile do
    get 'login', action: :login, as: 'login'
    post 'login', action: :login
    get 'logout', action: :login, as: 'logout'
    get 'show/:user_id', action: :show, as: :user
    get 'forgot_password', action: :forgot_password
  end

  resource :feedback, only: [:new, :create]
  get 'about/contact_us', to: 'about#contact_us', as: :contact_us


  if Rails.env.test?
    get '/call_me_in_test', to: 'dummy#call_me_in_test'
    post '/call_me_in_test', to: 'dummy#call_me_in_test'
    get '/api/:api_version/call_me_in_test', to: 'dummy#call_me_in_test', format: 'xml'
    post '/api/:api_version/call_me_in_test', to: 'dummy#call_me_in_test', format: 'xml'
    get '/raise_exception_for_test', to: 'dummy#raise_exception_for_test'
    get '/call_me_in_test', to: 'dummy#call_me_in_test'
    get '/check_in_test', to: 'dummy_planner_application#check_in_test'
  end
end

mingle-rails5/app/views/layouts/_application_hd.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<div id="header">
  <div id="header_wrapper">
    <div id='title' class="clear_float">
      <% if @content_for_mingle_logo %>
        <%= yield :mingle_logo %>
      <% else %>
        <% if MingleConfiguration.show_holiday_fun?(user_preference(:i_hate_holidays)) && MingleConfiguration.latest_holiday_name.present? %>
          <% img_tag = image_tag(MingleConfiguration.holiday_logo, {:"data-hover-src" => MingleConfiguration.holiday_logo_hover,
                                                                    :"data-src" => MingleConfiguration.holiday_logo, :class => MingleConfiguration.latest_holiday_name,
                                                                    :title => MingleConfiguration.show_holiday_fun?(user_preference(:i_hate_holidays)) ? MingleConfiguration.holiday_logo_tooltip : ''})%>
          <%= link_to "#{img_tag}".html_safe, landing_page, :id => 'logo_link', :class => "logo holiday #{MingleConfiguration.latest_holiday_name}" %>
        <% else %>
          <%= link_to "#{image_tag('/images/logo.png')}".html_safe, landing_page, :id => 'logo_link', :class => "logo" %>
            <%= yield :program_name %>
        <% end %>
      <% end %>

      <% if show_buy_button? && !CurrentLicense.status.free_tier? %>
        <% content_tag "div", :accessing => "account:edit", :id => "trial_count_down", :class => "clearfix" do %>
          <span class="cc">
          Days left:
          </span>
          <div class="days-left">
            <span><%= CurrentLicense.status.days_left.to_s.rjust(2, "0") %></span>
          </div>
          <div class="buy-button">
          <%= link_to "Buy", :url => {:action => "edit", :controller => "account"}, :id => "buy", :remote  => true  %>
          </div>
        <% end %>
      <% end %>

      <div class="header-actions clear_float">
        <ul class="actions_list">
          <li class="action_item">
            <%= yield :after_logo %>
          </li>
          <li class="action_item">
            <%= render :partial => 'shared/profile_utilities' unless defined?(hide_login) && hide_login %>
          </li>
        </ul>
      </div>
      <%= clear_float %>
    </div>
    <div>
      <% if @content_for_special_header %>
        <%= yield :special_header%>
      <% end %>
    </div>
    <%= yield :header_pills %>

  </div>
</div>
<% if @downgrade_view %>
  <%= javascript_with_rescue show_downgrade_lightbox %>
<% end %>

mingle-rails5/app/views/layouts/_flash.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<div id="flash">
  <%= render_flash_messages %>
</div>
<%= yield :macro_warnings %>

<%= clear_float %>

mingle-rails5/app/views/layouts/_foot_bar.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<div id="ft">
  <div class="quick-add-card">
	  <% # render cards/quick_add_menu  when required %>
  </div>
  <%  if controller.controller_name == 'cards' && controller.action_name == "list" && params[:style] == 'grid' %>
  <div class="team-list">
    <%= render :partial => 'team/team_list' if in_project_context? %>
  </div>
  <% end %>
  <% if invites_enabled? %>
    <div class="invite-to-team">
       <%= render :partial => 'team/invite_to_team' %>
    </div>
  <% end %>
  <% if show_low_on_licenses_alert?  %>
    <div class="low-on-licenses-alert">
      <span> <%= license_alert_message %> </span>
    </div>
  <% end %>
  <div class="also-viewing">
    <li class='also-viewing'><div id="notification" class="also-viewing-box" style="display: none;"></div></li>
  </div>

  <div class="footer-links">
    <ul id="support" class="clearfix">
      <% if show_buy_button? && CurrentLicense.status.free_tier? %>
        <li id="free-buy">
          <%= link_to "Buy", :url => {:action => "edit", :controller => "account"}, :title => CurrentLicense.status.trial_info, :id => "buy", remote: true %>
        </li>
      <% end %>
      <% if MingleConfiguration.saas? && !User.current.anonymous? %>
        <li>
          <% ajax_link(new_feedback_path) do %>
            Contact us
          <% end %>
        </li>
      <% end %>
      <li>
        <% ajax_link(contact_us_path) do %>
          Help
        <% end %>
      </li>
      <%= render :partial => "shared/hotkey_help_icon" %>
      <%= render :partial => "shared/footer_notification" %>
      <%= render :partial => 'shared/copyright' %>
      <%= render :partial => 'shared/holiday_links' %>
    </ul>
  </div>

</div>

<%= javascript_with_rescue <<-JAVASCRIPT
  $j(".invite-to-team").inviteToTeam();
  $j("#ft .low-on-licenses-alert").showContactAdministratorMessage();
  JAVASCRIPT
%>

mingle-rails5/app/views/layouts/_metrics.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<% if MingleConfiguration.pingdom_rum_id %>
  <script src="//rum-static.pingdom.net/pa-<%=MingleConfiguration.pingdom_rum_id%>.js" async></script>
<% end %>

<% if metrics_enabled? %>
   <!-- start Mixpanel -->
   <script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);

    mixpanel.init('<%= MingleConfiguration.metrics_api_key %>')
    mixpanel.register(<%= monitoring_events_meta_data.to_json.html_safe %>);

    mixpanel.identify('<%= monitoring_events_user_id %>');
  </script><!-- end Mixpanel -->
<%- end -%>

mingle-rails5/app/views/layouts/_readonly_warning.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<% if MingleConfiguration.readonly_mode? %>
  <div id="readonly-warning" class="info-box">
    <div>
      <h4>Mingle is now read-only</h4>
      <a class="link" href="https://www.thoughtworks.com/mingle/news/2018/07/31/mingle-is-retiring.html" target="_blank">Mingle is being retired on July 31st 2019.</a><br />
      From now on, you will not be able to create new cards, add new users or make any changes. Mingle administrators
      can use the <a class="link" href="/exports">Export</a> feature to export all Mingle data.<br />
      Please contact <a class="link" href="mailto:support@thoughtworks.com">support@thoughtworks.com</a> if you have any questions.
    </div>
  </div>
<% end %>

mingle-rails5/app/views/layouts/application.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<!DOCTYPE html>
<html>
  <head>
    <title>MingleBackend</title>

    <%= rails2_compatible_stylesheet_link_tag :sprockets_app_css %>
    <%= rails2_compatible_javascript_include_tag :sprockets_app_js %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mingle-rails5/app/views/layouts/error.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <title><%= page_title %></title>
	<%= rails2_compatible_stylesheet_link_tag :sprockets_app_css %>
	<%= rails2_compatible_javascript_include_tag :sprockets_app_js %>
  <link rel="shortcut icon" href="<%= image_path('/favicon.ico') %>" />
</head>

<body>
  <div id="doc" class="<%= if @sidebar then 'yui-t6' else 'yui-t7' end %>">
    <%= render :partial => 'layouts/application_hd', :locals => { :hide_login => true } %>

    <div id="bd">
      <div id="yui-main">
        <div class="yui-b" id="main">
          <div class="main_inner">
          <%= yield %>
          </div>
        </div>
      </div>
    </div>
</div>

  <%= render_buffered_javascript %>
</body>

</html>

mingle-rails5/app/views/layouts/saas_tos.html.erb
<%# 
Copyright 2020 ThoughtWorks, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
-%>
<!DOCTYPE html>

<html>
<head>
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <title><%= h page_title %></title>

  <%= stylesheet_link_tag("sprockets_app") %>
  <%= stylesheet_link_tag("install") %>
  <%= stylesheet_link_tag("print", :media => 'print') %>

  <%= raw(yield(:stylesheets)) -%>
  <%= render partial: 'layouts/metrics' %>
  <%= javascript_include_tag("sprockets_app") %>

  <link rel="shortcut icon" href="<%= image_path('/favicon.ico') %>" />
  <link rel="apple-touch-icon" href="<%= image_path('/apple-touch-icon.png') %>" />
</head>

<body id="saas-tos">
  <div id="doc" class="yui-t7">
    <div id='hd'>
      <div id="hd-top">
        <div id="title">
        </div>
        <div class='clear-both'><!-- Clear floats --></div>
      </div>
    </div>
    <div id="bd">
      <div id="yui-main">
        <div class="yui-b" id="main">
          <div class='main_inner'>
            <%= yield %>
            <div class='ie-margin-collapse-fix'>&nbsp;</div>
          </div>
        </div>
      </div>
    </div>

    <div id="ft">
      <ul id="support">
        <li id="support_request"><a href="{% supportUrl %}">Support request</a></li>
        <li id="community"><a href="{% communityHome %}">Community</a></li>
        <li><a href='{% helpPath %}/index.html'>Help</a></li>
      </ul>
    </div>
  </div>
  <div id="state" style="display:none">{% currentState %}</div>
</body>
</html>